### ISSUE TITLE
RHTAP and buildpack Epic

### ISSUE THREAD

**Issue by cmoulliard** [redhat-buildpacks/testing#22]
## Todo

- [x] Import the README instructions from the halkyionio/rhtap-templates and create a new section about RHTAP
- [x] Support a new parameter to specify the type of event: push, pull request
- [ ] Prepare a demo for RHTAP teams
- [ ] Create slides introducing RHTAP + buildpacks

## Issues
- [x] Report the issue: build created as pull_request while no PR has been pulled --> [see issue 23](https://github.com/redhat-buildpacks/testing/issues/23)
- [x] Automate e2e scenario to 100%
- [ ] Route do not consume the proper pod -> [see issue 24](https://github.com/redhat-buildpacks/testing/issues/24)
- [x] Paketo SBOM generated cannot be read by the show-sbom task - fixed using [grype task](https://github.com/halkyonio/rhtap-templates/commit/ff9bb952909b22f280b9ebe68f0cf4207a969bae)
 
## Requirements
- [ ] What about testing a scenario where micro1 -> micro2
- [ ] How to create a Cluster provisioned with needed components and access it as environment
- [ ] What about ServiceBinding
- [ ] Standalone installation
- [ ] RHTAP as CI platform ?

**Comment by cmoulliard** [comment]
<img width="1737" alt="Screenshot 2023-08-04 at 11 02 17" src="https://github.com/redhat-buildpacks/testing/assets/463790/280e029d-b1ed-4c2e-98e4-f5c8deba4a29">
