### ISSUE TITLE
Bump project to use lifecycle - 0.17.0

### ISSUE THREAD

**Issue by cmoulliard** [redhat-buildpacks/testing#25]
## Todo

- [x] Bump project to use lifecycle - 0.17.0
- [x] Remove the if condition of the github actions
- [x] Document what is new part of lifecycle 0.17
- [x] Find a way to been able to test using different versions of lifecycle: 0.16.5, 0.17
