### ISSUE TITLE
Add the new step: extender

### ISSUE THREAD

**Issue by cmoulliard** [redhat-buildpacks/testing#37]
## Todo

Add the new step: [extender](https://github.com/buildpacks/spec/blob/main/platform.md#extender-optional-and-experimental) supported since lifecycle - 0.17 within the Tekton Buildpack Task

Remarks from @BarDweller 

- [x] restore isn't being passed --build-image
- [x] restore isn't being passed /kaniko mount
- [ ]  you have both extender and build phases in the yaml, the two are mutually exclusive. Use extender for builders with extensions (it drives build internally), and use build for builders without extensions.
- [ ] Document on the README.md page how to use the extender
- [x] all phases should be running against the builder image, you have lifecycle image set for restore/analyze/export. This could result in a build using different lifecycle versions for different phases, which would result in undefined behavior. Always use the builder image, and if you need to override lifecycle version, then you have to do that by mounting it in
- [x] all phases should be invoked as the userid/groupid retrieved from the builder image env (can inspect the image to retrieve this before execution).. except the extender phase that must be invoked as 0:0 .. the -uid/-gid params are used to pass the non-root uid/gid to the extender to use during the build phase.
- [x] you should set CNB_PLATFORM_API to the level of the platform api you are supporting (at least 0.10 for extensions, 0.12 is current) and pass that to each phase as environment.
- [x] CNB_EXPERIMENTAL_MODE should be passed to each phase consistently as environment.
- [x] configure --log-level for each phase too.

**Comment by cmoulliard** [comment]
Tekton job report: `[buildpacks : extender] ERROR: stat /kaniko: no such file or directory`

**Comment by cmoulliard** [comment]
Tekton job report: `failed to extend build image: getting build image to extend: failed to get digest for reference '': a digest must contain exactly one '@' separator (e.g. registry/repository@digest) saw: `

**Comment by cmoulliard** [comment]
To be fixed part of the Task
```
[buildpacks : extender] 2023/08/24 12:38:11 warning: unsuccessful cred copy: ".docker" from "/tekton/creds" to "/tekton/home": unable to open destination: open /tekton/home/.docker/config.json: permission denied
```

**Comment by cmoulliard** [comment]
Getting this error after fixing points reported by ozzy
```
[buildpacks : extender] Extending base image for build: index.docker.io/paketocommunity/build-ubi-base@sha256:054b6033eae14b78a9542bb457faf4682ddadeb54da9dfc7b6cd443ec40d732c
[buildpacks : extender] Found build Dockerfile for extension 'paketo-community/ubi-nodejs-extension'
[buildpacks : extender] Applying Dockerfile at /layers/generated/build/paketo-community_ubi-nodejs-extension/Dockerfile to 'base@sha256:566187b63a2bed9adeac355e07121560f658758e547250b226cce6d6851cea55'...
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="Built cross stage deps: map[]"
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="Executing 0 build triggers"
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="Building stage 'base@sha256:566187b63a2bed9adeac355e07121560f658758e547250b226cce6d6851cea55' [idx: '0', base-idx: '-1']"
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="Cmd: USER"
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="Checking for cached layer oci:/kaniko/cache/layers/cached:5e2ccc418aacefc882893b1be461a86dca084b185971aef92e378f3b0ae89126..."
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="No cached layer found for cmd RUN echo ${build_id}"
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="Cmd: USER"
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="Unpacking rootfs as cmd RUN echo ${build_id} requires it."
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="Skipping unpacking as no commands require it."
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="USER root"
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="Cmd: USER"
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="No files changed in this command, skipping snapshotting."
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="ARG build_id=0"
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="No files changed in this command, skipping snapshotting."
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="RUN echo ${build_id}"
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="Initializing snapshotter ..."
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="Taking snapshot of full filesystem..."
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="Cmd: /bin/sh"
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="Args: [-c echo ${build_id}]"
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="Util.Lookup returned: &{Uid:0 Gid:0 Username:root Name:root HomeDir:/root}"
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="Performing slow lookup of group ids for root"
[buildpacks : extender] time="2023-08-24T14:07:30Z" level=info msg="Running: [/bin/sh -c echo ${build_id}]"
[buildpacks : extender] Timer: Extender ran for 36.450875ms and ended at 2023-08-24T14:07:30Z
[buildpacks : extender] ERROR: failed to extend build image: extending build image: applying Dockerfile to image: error building stage: failed to execute command: starting command: fork/exec /bin/sh: operation not permitted

[buildpacks : build] 2023/08/24 14:07:30 Skipping step because a previous step failed

[buildpacks : export] 2023/08/24 14:07:16 warning: unsuccessful cred copy: ".docker" from "/tekton/creds" to "/tekton/home": unable to open destination: open /tekton/home/.docker/config.json: permission denied
[buildpacks : export] 2023/08/24 14:07:31 Skipping step because a previous step failed

failed to get logs for task buildpacks : container step-export has failed  : [{"key":"StartedAt","value":"2023-08-
```
